name = "api"
main = "./src/index.ts"
compatibility_date = "2023-04-24"

account_id = "ba4e8f7f9ffbc23dba6acd0d9bd3ef46"
workers_dev = true

[[r2_buckets]]
binding = 'FILES_BUCKET'
bucket_name = 'files'
preview_bucket_name = 'files'

[durable_objects]
bindings = [
  {name = "RATE_LIMITER", class_name = "RateLimiter" },
]

[[migrations]]
tag = "v1"
new_classes = ["RateLimiter"]

[vars]
ENVIRONMENT = "DEV"

[env.production.vars]
ENVIRONMENT = "PROD"