name = "api-wanderer-moe"
main = "./src/index.js"
compatibility_date = "2023-04-24"

account_id = "ba4e8f7f9ffbc23dba6acd0d9bd3ef46"
workers_dev = true

[[r2_buckets]]
binding = 'bucket'
bucket_name = 'wanderer-moe'
preview_bucket_name = 'wanderer-moe'

[[d1_databases]]
binding = 'database'
database_name = 'wanderer-moe-requests'
database_id = '9c180d14-7f79-45c6-b2f5-809b4e75941b'

[vars]