name = "api-wanderer-moe"
main = "./src/index.ts"
compatibility_date = "2023-04-24"

account_id = "ba4e8f7f9ffbc23dba6acd0d9bd3ef46"
workers_dev = true

[[r2_buckets]]
binding = 'bucket'
bucket_name = 'wanderer-moe'
preview_bucket_name = 'wanderer-moe'

[[d1_databases]]
binding = 'database'
database_name = 'wanderer-moe'
database_id = 'df7af4d9-3546-42d2-bf0d-8376091a7875'

[vars]
