name: Run Tests
on:
    push:
        branches:
            - "*"

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest
        timeout-minutes: 5
        # local sqld instance for "turso dev"
        services:
            sqld:
                image: ghcr.io/libsql/sqld:latest
                ports:
                    - 8080:8080

        env:
            ENVIRONMENT: DEV
            TURSO_DEV_DATABASE_URL: http://127.0.0.1:8080

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20.9.0

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest
                  run_install: false

            - name: Install dependencies
              run: pnpm install

            - name: Create .dev.vars file
              run: |
                  echo ENVIRONMENT=$ENVIRONMENT >> .dev.vars
                  echo TURSO_DEV_DATABASE_URL=$TURSO_DEV_DATABASE_URL >> .dev.vars

            - name: Initialize Drizzle
              run: pnpm drizzle:dev:init
